//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnouncementsPremiumsRef
    {
        public int Id { get; set; }
        public int AdId { get; set; }
        public int AdSectionId { get; set; }
        public int PremiumId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ExpiresAt { get; set; }
    
        public virtual Announcement Announcement { get; set; }
        public virtual Premium Premium { get; set; }
        public virtual Section Section { get; set; }
    }
}
