//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public Announcement()
        {
            this.AnnouncementBookmarks = new HashSet<AnnouncementBookmarks>();
            this.AnnouncementComments = new HashSet<AnnouncementComments>();
            this.AnnouncementImages = new HashSet<AnnouncementImages>();
            this.AnnouncementsPremiumsRef = new HashSet<AnnouncementsPremiumsRef>();
            this.ComputerAnnouncementRef = new HashSet<ComputerAnnouncementRef>();
            this.PopularAnnouncements = new HashSet<PopularAnnouncements>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsAuction { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int SectionId { get; set; }
        public string SmallDescription { get; set; }
        public int SubsectionId { get; set; }
        public int CategoryId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CityId { get; set; }
        public int CurrencyId { get; set; }
        public int ViewsCount { get; set; }
        public bool IsDisplayPhone { get; set; }
        public System.DateTime UpTime { get; set; }
        public System.DateTime ExpiredAt { get; set; }
        public string Phone { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual Section Section { get; set; }
        public virtual Subsection Subsection { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<AnnouncementBookmarks> AnnouncementBookmarks { get; set; }
        public virtual ICollection<AnnouncementComments> AnnouncementComments { get; set; }
        public virtual ICollection<AnnouncementImages> AnnouncementImages { get; set; }
        public virtual ICollection<AnnouncementsPremiumsRef> AnnouncementsPremiumsRef { get; set; }
        public virtual ICollection<ComputerAnnouncementRef> ComputerAnnouncementRef { get; set; }
        public virtual ICollection<PopularAnnouncements> PopularAnnouncements { get; set; }
    }
}
