//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnouncementConfig
    {
        public int Id { get; set; }
        public string Slogan { get; set; }
        public int Premium1Id { get; set; }
        public int Premium2Id { get; set; }
        public int Premium3Id { get; set; }
    
        public virtual Premium Premium { get; set; }
        public virtual Premium Premium1 { get; set; }
        public virtual Premium Premium2 { get; set; }
    }
}
