//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public Articles()
        {
            this.ActualArticle = new HashSet<ActualArticle>();
            this.ArticleComment = new HashSet<ArticleComment>();
            this.ArticleConfig = new HashSet<ArticleConfig>();
            this.ArticleConfig1 = new HashSet<ArticleConfig>();
            this.ArticleConfig2 = new HashSet<ArticleConfig>();
            this.ArticleConfig3 = new HashSet<ArticleConfig>();
            this.MainPageArticleConfigs = new HashSet<MainPageArticleConfigs>();
            this.MainPageArticleConfigs1 = new HashSet<MainPageArticleConfigs>();
            this.MainPageArticleConfigs2 = new HashSet<MainPageArticleConfigs>();
            this.MainPageArticleConfigs3 = new HashSet<MainPageArticleConfigs>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Slug { get; set; }
        public bool IsActive { get; set; }
        public int ViewsCount { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Logo { get; set; }
        public string SmallDescription { get; set; }
        public int SubsectionId { get; set; }
    
        public virtual ICollection<ActualArticle> ActualArticle { get; set; }
        public virtual ICollection<ArticleComment> ArticleComment { get; set; }
        public virtual ICollection<ArticleConfig> ArticleConfig { get; set; }
        public virtual ICollection<ArticleConfig> ArticleConfig1 { get; set; }
        public virtual ICollection<ArticleConfig> ArticleConfig2 { get; set; }
        public virtual ICollection<ArticleConfig> ArticleConfig3 { get; set; }
        public virtual ICollection<MainPageArticleConfigs> MainPageArticleConfigs { get; set; }
        public virtual ICollection<MainPageArticleConfigs> MainPageArticleConfigs1 { get; set; }
        public virtual ICollection<MainPageArticleConfigs> MainPageArticleConfigs2 { get; set; }
        public virtual ICollection<MainPageArticleConfigs> MainPageArticleConfigs3 { get; set; }
    }
}
