//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogSecondCategory
    {
        public CatalogSecondCategory()
        {
            this.CatalogParamSubsection = new HashSet<CatalogParamSubsection>();
            this.CatalogThirdCategory = new HashSet<CatalogThirdCategory>();
            this.NewSectionInCatalog = new HashSet<NewSectionInCatalog>();
            this.PopularSectionInCatalog = new HashSet<PopularSectionInCatalog>();
            this.Product = new HashSet<Product>();
            this.ShopCategoryRef = new HashSet<ShopCategoryRef>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public bool isNew { get; set; }
        public bool isActive { get; set; }
    
        public virtual CatalogCategory CatalogCategory { get; set; }
        public virtual ICollection<CatalogParamSubsection> CatalogParamSubsection { get; set; }
        public virtual ICollection<CatalogThirdCategory> CatalogThirdCategory { get; set; }
        public virtual ICollection<NewSectionInCatalog> NewSectionInCatalog { get; set; }
        public virtual ICollection<PopularSectionInCatalog> PopularSectionInCatalog { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ShopCategoryRef> ShopCategoryRef { get; set; }
    }
}
