//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogConfigTable
    {
        public int Id { get; set; }
        public string Slogan { get; set; }
        public string PromoText { get; set; }
        public string WarningText { get; set; }
        public string RegShopPromoText { get; set; }
    }
}
