//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryParameter
    {
        public CategoryParameter()
        {
            this.ProductParameterValue = new HashSet<ProductParameterValue>();
        }
    
        public int ID { get; set; }
        public int SectionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual CategoryParametersSection CategoryParametersSection { get; set; }
        public virtual ICollection<ProductParameterValue> ProductParameterValue { get; set; }
    }
}
