//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Announcement = new HashSet<Announcement>();
            this.Realty = new HashSet<Realty>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Announcement> Announcement { get; set; }
        public virtual ICollection<Realty> Realty { get; set; }
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
