//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public Computer()
        {
            this.ComputerAnnouncementRef = new HashSet<ComputerAnnouncementRef>();
            this.ComputerRealtyRef = new HashSet<ComputerRealtyRef>();
        }
    
        public int Id { get; set; }
        public string Key { get; set; }
    
        public virtual ICollection<ComputerAnnouncementRef> ComputerAnnouncementRef { get; set; }
        public virtual ICollection<ComputerRealtyRef> ComputerRealtyRef { get; set; }
    }
}
