//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public Images()
        {
            this.Banners = new HashSet<Banners>();
        }
    
        public int ID { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<Banners> Banners { get; set; }
    }
}
