//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainPageArticleConfigs
    {
        public int Id { get; set; }
        public Nullable<int> Article1Id { get; set; }
        public Nullable<int> Article2Id { get; set; }
        public Nullable<int> Article3Id { get; set; }
        public Nullable<int> Article4Id { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Articles Articles1 { get; set; }
        public virtual Articles Articles2 { get; set; }
        public virtual Articles Articles3 { get; set; }
    }
}
