//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.MenuPageRef = new HashSet<MenuPageRef>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> PageTemplateId { get; set; }
        public string Slug { get; set; }
    
        public virtual ICollection<MenuPageRef> MenuPageRef { get; set; }
    }
}
