//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public decimal Cost { get; set; }
        public int PaysystemInvId { get; set; }
        public int AdId { get; set; }
        public int SiteCategory { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Status { get; set; }
        public Nullable<int> PremiumId { get; set; }
        public Nullable<int> SectionId { get; set; }
    }
}
