//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premium
    {
        public Premium()
        {
            this.AnnouncementConfig = new HashSet<AnnouncementConfig>();
            this.AnnouncementConfig1 = new HashSet<AnnouncementConfig>();
            this.AnnouncementConfig2 = new HashSet<AnnouncementConfig>();
            this.AnnouncementsPremiumsRef = new HashSet<AnnouncementsPremiumsRef>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public int Lifetime { get; set; }
    
        public virtual ICollection<AnnouncementConfig> AnnouncementConfig { get; set; }
        public virtual ICollection<AnnouncementConfig> AnnouncementConfig1 { get; set; }
        public virtual ICollection<AnnouncementConfig> AnnouncementConfig2 { get; set; }
        public virtual ICollection<AnnouncementsPremiumsRef> AnnouncementsPremiumsRef { get; set; }
    }
}
