//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessages
    {
        public int Id { get; set; }
        public int SenderId { get; set; }
        public int RecepientId { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<int> UserProfile_UserId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual UserProfile UserProfile2 { get; set; }
    }
}
