//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSectionParamRef
    {
        public int Id { get; set; }
        public int ParamId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual CatalogCategory CatalogCategory { get; set; }
        public virtual ProductParam ProductParam { get; set; }
    }
}
