//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public long ID { get; set; }
        public long ProductID { get; set; }
        public string ImageName { get; set; }
        public bool IsTitular { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
