//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductParameterValue
    {
        public long ProductID { get; set; }
        public int CategoryParameterID { get; set; }
        public string Value { get; set; }
        public Nullable<int> UnitID { get; set; }
    
        public virtual CategoryParameter CategoryParameter { get; set; }
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
