//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductParam
    {
        public ProductParam()
        {
            this.ProductParamValue = new HashSet<ProductParamValue>();
            this.ProductSectionParamRef = new HashSet<ProductSectionParamRef>();
            this.ProductSubsectionParamRef = new HashSet<ProductSubsectionParamRef>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductParamValue> ProductParamValue { get; set; }
        public virtual ICollection<ProductSectionParamRef> ProductSectionParamRef { get; set; }
        public virtual ICollection<ProductSubsectionParamRef> ProductSubsectionParamRef { get; set; }
    }
}
