//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductBookmark = new HashSet<ProductBookmark>();
            this.ProductFeedback = new HashSet<ProductFeedback>();
            this.ProductImage = new HashSet<ProductImage>();
            this.ProductParameterValue = new HashSet<ProductParameterValue>();
            this.ShopProduct = new HashSet<ShopProduct>();
        }
    
        public long ID { get; set; }
        public int CategoryID { get; set; }
        public int ManufacturerID { get; set; }
        public string ReviewLink { get; set; }
        public string Title { get; set; }
        public string SmallDescription { get; set; }
        public string Description { get; set; }
        public bool IsPopular { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<ProductBookmark> ProductBookmark { get; set; }
        public virtual ICollection<ProductFeedback> ProductFeedback { get; set; }
        public virtual ICollection<ProductImage> ProductImage { get; set; }
        public virtual ICollection<ProductParameterValue> ProductParameterValue { get; set; }
        public virtual ICollection<ShopProduct> ShopProduct { get; set; }
    }
}
