//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realty
    {
        public Realty()
        {
            this.ComputerRealtyRef = new HashSet<ComputerRealtyRef>();
            this.RealtyBookmark = new HashSet<RealtyBookmark>();
            this.RealtyPaymentHistory = new HashSet<RealtyPaymentHistory>();
            this.RealtyPayment = new HashSet<RealtyPayment>();
            this.RealtyPhoto = new HashSet<RealtyPhoto>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ExpiredAt { get; set; }
        public System.DateTime UpTime { get; set; }
        public bool IsActive { get; set; }
        public bool IsAuction { get; set; }
        public bool IsAgency { get; set; }
        public int UserId { get; set; }
        public int Views { get; set; }
        public bool WithExtension { get; set; }
        public bool WithGarage { get; set; }
        public bool WithBasement { get; set; }
        public bool WithGarden { get; set; }
        public Nullable<bool> ForDays { get; set; }
        public Nullable<double> CeillingHeight { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> FloorCount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<byte> RoomsCount { get; set; }
        public Nullable<double> Square { get; set; }
        public string Name { get; set; }
        public string SmallDescription { get; set; }
        public string Description { get; set; }
        public string Street { get; set; }
        public string AgencyName { get; set; }
        public int CategoryId { get; set; }
        public int CurrencyId { get; set; }
        public int CityId { get; set; }
        public int SectionId { get; set; }
        public bool IsDisplayPhone { get; set; }
        public string Phone { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<ComputerRealtyRef> ComputerRealtyRef { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual RealtyCategory RealtyCategory { get; set; }
        public virtual RealtySection RealtySection { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<RealtyBookmark> RealtyBookmark { get; set; }
        public virtual ICollection<RealtyPaymentHistory> RealtyPaymentHistory { get; set; }
        public virtual ICollection<RealtyPayment> RealtyPayment { get; set; }
        public virtual ICollection<RealtyPhoto> RealtyPhoto { get; set; }
    }
}
