//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealtyPayment
    {
        public int Id { get; set; }
        public double Cost { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int RealtyId { get; set; }
        public System.Guid TransactionId { get; set; }
        public int UserId { get; set; }
    
        public virtual Realty Realty { get; set; }
    }
}
