//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopProduct
    {
        public int ShopID { get; set; }
        public long ProductID { get; set; }
        public int ShopProductStatusID { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual ShopProductStatus ShopProductStatus { get; set; }
    }
}
