//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.ShopFeedback = new HashSet<ShopFeedback>();
            this.ShopProduct = new HashSet<ShopProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CityID { get; set; }
        public double Debt { get; set; }
        public string Logo { get; set; }
        public string Site { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string FullTitle { get; set; }
        public string CompanyName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool Sunday { get; set; }
        public string Requisites { get; set; }
        public string Icq { get; set; }
        public string Skype { get; set; }
    
        public virtual ICollection<ShopFeedback> ShopFeedback { get; set; }
        public virtual ICollection<ShopProduct> ShopProduct { get; set; }
    }
}
