//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsection
    {
        public Subsection()
        {
            this.Announcement = new HashSet<Announcement>();
            this.NewInCatalog = new HashSet<NewInCatalog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SectionId { get; set; }
        public bool IsNew { get; set; }
    
        public virtual ICollection<Announcement> Announcement { get; set; }
        public virtual ICollection<NewInCatalog> NewInCatalog { get; set; }
        public virtual Section Section { get; set; }
    }
}
