// <auto-generated />
namespace Reklama.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Fuck2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fuck2));
        
        string IMigrationMetadata.Id
        {
            get { return "201309081538292_Fuck2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
