// <auto-generated />
namespace Reklama.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class maxLengthOfFieldValueForTableProductParamSetTo1000 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(maxLengthOfFieldValueForTableProductParamSetTo1000));
        
        string IMigrationMetadata.Id
        {
            get { return "201310121432456_maxLengthOfFieldValueForTableProductParamSetTo1000"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
