// <auto-generated />
namespace Reklama.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddParamSubsectionIdToProductParamValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddParamSubsectionIdToProductParamValues));
        
        string IMigrationMetadata.Id
        {
            get { return "201309091922081_AddParamSubsectionIdToProductParamValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
