// <auto-generated />
namespace Reklama.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addxzmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addxzmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201401111419411_addxzmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
