// <auto-generated />
namespace Reklama.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class somewitharticlesonmainpage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(somewitharticlesonmainpage));
        
        string IMigrationMetadata.Id
        {
            get { return "201401121343398_somewitharticlesonmainpage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
