// <auto-generated />
namespace Reklama.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_IsActive_To_Suncategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IsActive_To_Suncategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201404190815444_Add_IsActive_To_Suncategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
