// <auto-generated />
namespace Reklama.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_IsTitular_To_Realty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IsTitular_To_Realty));
        
        string IMigrationMetadata.Id
        {
            get { return "201404110748442_Add_IsTitular_To_Realty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
