// <auto-generated />
namespace Reklama.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_ComputerRealtyRef1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_ComputerRealtyRef1));
        
        string IMigrationMetadata.Id
        {
            get { return "201403181456270_Add_ComputerRealtyRef1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
